import "./globals.css";
import { Inter } from "next/font/google";
import type { INormalLayoutProps } from "@/utils/interfaces";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: INormalLayoutProps) {
  console.log(props.params.lang);
  return (
    <html lang={props.params.lang}>
      <body className={inter.className}>{props.children}</body>
    </html>
  );
}
